#!/bin/sh

# Note this gets executed INSIDE the outer jail not on the host!

brand_root="$1"
jail_root="$2"
uuid="$3"
hostname="$4"

# include shared utility functions
. ${brand_root}/../shared/utils.sh
. ${brand_root}/lx-utils.sh

validate_root "${jail_root}"

distro=$(detect_distro "${jail_root}/root/jail")


if [ "${distro}" = "redhat" ]
then
    init_script='/bin/sh /etc/rc.d/rc 3'
else
    echo "unsupported distro"
    exit 1
fi

# create
jail -c persist \
     "name=${uuid}" \
     "host.hostname=${hostname}" \
     path=/jail \
     ip4=inherit \
     devfs_ruleset=4 \
     securelevel=2 \
     sysvmsg=new \
     sysvsem=new \
     sysvshm=new \
     allow.raw_sockets \
     exec.start="${init_script}"
