#!/bin/sh

# Note this gets executed INSIDE the outer jail not on the host!

# include shared utility functions
. ../shared/utils.sh


uuid="$1"
hostname="$2"

# create
jail -c persist \
     "name=${uuid}" \
     "host.hostname=${hostname}" \
     path=/jail \
     ip4=inherit \
     devfs_ruleset=4 \
     securelevel=2 \
     sysvmsg=new \
     sysvsem=new \
     sysvshm=new \
     allow.raw_sockets \
     exec.start='/bin/sh /etc/rc'
