#!/bin/sh

# include shared utility functions
. ../shared/utils.sh
jail_root="$1"
inner_id="$2"

validate_root "${jail_root}"

# outer jail
umount ${jail_root}/root/dev
# inner jail
umount ${jail_root}/root/jail/dev

umount ${jail_root}/root/jail/proc
umount ${jail_root}/root/jail/sys
