#!/bin/sh

# include shared utility functions
. ../shared/utils.sh
jail_root="$1"
brand_root="$2"

validate_root "${jail_root}"

# delete the old brand
echo rm -r ${jail_root}/root$(dirname ${brand_root})

# create a new folder for the brand
echo mkdir -p ${jail_root}/root$(dirname ${brand_root})

# copy over our brand
echo cp -r ${brand_root} ${jail_root}/root$(dirname ${brand_root})

# mount devfs (not sure about this)

# outer jail
mount -t devfs devfs ${jail_root}/root/dev
# inner jail
mount -t devfs devfs ${jail_root}/root/jail/dev

# mount linux specific fs's
mount -t linprocfs linprocfs ${jail_root}/root/jail/proc
mount -t linsysfs linsysfs ${jail_root}/root/jail/sys
