#!/bin/sh

# include shared utility functions
brand_root="$1"
jail_root="$2"
inner_id="$3"

. ${brand_root}/../shared/utils.sh

validate_root "${jail_root}"


# cleanly shut down the inner jail (should this be run inside the outer jail?)
if [ ! -z "${inner_id}" ]
then
    jexec ${inner_id} /bin/sh /etc/rc.shutdown
fi

# outer jail
umount ${jail_root}/root/dev
# inner jail
umount ${jail_root}/root/jail/dev
