#!/bin/sh

brand_root="$1"
jail_root="$2"

# include shared utility functions
. ${brand_root}/../shared/utils.sh

validate_root "${jail_root}"

# delete the old brand
echo rm -r ${jail_root}/root$(dirname ${brand_root})

# create a new folder for the brand
echo mkdir -p ${jail_root}/root$(dirname ${brand_root})

# copy over our brand
echo cp -r ${brand_root} ${jail_root}/root$(dirname ${brand_root})

# mount devfs (not sure about this)

# outer jail
mount -t devfs devfs ${jail_root}/root/dev
# inner jail
mount -t devfs devfs ${jail_root}/root/jail/dev
