#!/bin/sh

brand_root="$1"
jail_root="$2"

# include shared utility functions
. ${brand_root}/../shared/utils.sh

validate_root "${jail_root}"

brands_src=$(dirname ${brand_root})
brands_target="${jail_root}/root/${brands_src}"

# delete the old brand
rm -r ${brands_target}

# create a new folder for the brand
mkdir -p ${brands_target}

# copy over our brand
cp -r ${brand_root} ${brands_target}
cp -r ${brands_src}/share ${brands_target}

# mount devfs (not sure about this)

# outer jail
mount -t devfs devfs ${jail_root}/root/dev
# inner jail
mount -t devfs devfs ${jail_root}/root/jail/dev
