#!/bin/sh

brand_root="$1"
jail_root="$2"

# include shared utility functions
. ${brand_root}/../shared/utils.sh


validate_root "${jail_root}"

clean_outer_root "${jail_root}"

# create bas

dirs="bin dev mnt proc tmp etc/defaults"
for dir in ${dirs}
do
    mkdir -p ${jail_root}/root/${dir}
    chown root:wheel ${jail_root}/root/${dir}
    chmod 775 ${jail_root}/root/${dir}
done

cp /etc/defaults/devfs.rules ${jail_root}/$ID/root/etc/defaults

## required files:
execs='/libexec/ld-elf.so.1 /bin/sh /sbin/ifconfig /sbin/route /usr/sbin/jail'
files=""
## inlcude libraries that are needed
for e in ${execs}
do
    files="${files} $(ldd -a $e 2> /dev/null | awk '/=>/{print $(NF-1)}')"
    files="${files} ${e}"
done

## copy the files in the zone root
for file in ${files}
do
    mkdir -p ${jail_root}/root$(dirname ${file})
    cp ${file} ${jail_root}/root${file}
done

# install the branch information

mkdir -p ${jail_root}/root$(dirname ${brand_root})
cp -r ${brand_root} ${jail_root}/root$(dirname ${brand_root})

mkdir -p ${jail_root}/root$(dirname ${brand_root})/../shared
cp -r ${brand_root} ${jail_root}/root$(dirname ${brand_root})/../shared


if [ -f "${jail_root}/root/config/resolvers" ]
then
    for r in $(cat "${jail_root}/root/config/resolvers")
    do
        echo "nameserver ${r}" >> ${jail_root}/root/jail/etc/resolv.conf
    done
fi

if [ -f "${jail_root}/root/config/root_authorized_keys" ]
then
    mkdir -p "${jail_root}/root/jail/root/.ssh"
    cp "${jail_root}/root/config/root_authorized_keys" "${jail_root}/root/jail/root/.ssh/authorized_keys"
fi

#TODO: network config:
# * get resolvers and set them resolvers
# * routs? (do we need to set them?)
#TODO: get rood autorized keys set set them
