#!/bin/sh

if [ ! -d /usr/local/etc/vmadm  ]
then 
    mkdir -p /usr/local/etc/vmadm
fi

if [ ! -d /var/imgadm/images ]
then 
    mkdir -p /var/imgadm/images
fi


CONFFILE="/usr/local/etc/vmadm.toml"
if [ ! -f $CONFFILE ]
then
    echo "Creating new configuration from example file."
    cat <<EOF > $CONFFILE
pool = "zroot/jails"
[networks]
admin = "bridge0"
EOF
else
    echo "Please make sure you update your config according to the update manual!"
fi
